#include <stdio.h>

int main() {
	
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");
	printf("mArC DOESN'T KNOW HOW TO PROGRAM COLLIDERS :)");

	return 0;
}